// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ditheto-hero/Current.tsx": () => import("../components/mockups/ditheto-hero/Current.tsx"),
  "./components/mockups/ditheto-hero/Updated.tsx": () => import("../components/mockups/ditheto-hero/Updated.tsx")
};
